### ISSUE TITLE
Show bike facilities, even if not primary/secondary/tertiary highway

### ISSUE THREAD

**Issue by trivisonno** [trivisonno/cycleway-stats#2]
Colored lines will only appear if the highway is a cycleway/primary/secondary/tertiary (or _links of these). Residential streets with shared_lane, lane, etc are not shown by default, unless you mouseover them. This ignores the presence of intentional bike routes that may be designed through residential areas, for example.

However, there may exist edge cases where large portions of the residential street network include bike facilities, and it may create some amount of visual "clutter". A toggle option may also be useful for this feature.

**Comment by trivisonno** [comment]
@schnuerle, can you provide an example OSM way for a residential street with a sharrow? I have none in Cleveland to test...

**Comment by schnuerle** [comment]
Here is one, and there are a few others connecting to this: 

https://www.openstreetmap.org/way/736418158

https://cyclestreetstats.s3.amazonaws.com/crosssection.html?id=736418158
