### ISSUE TITLE
lanesBackwards cause JavaScript error

### ISSUE THREAD

**Issue by schnuerle** [trivisonno/cycleway-stats#44]
This may be an easy fix, but I came across a way that threw a JS error.

https://cyclestreetstats.s3.amazonaws.com/crosssection.html?id=522063561

`Uncaught ReferenceError: lanesBackward is not defined - osmtostreetmix.js:325`

**Comment by trivisonno** [comment]
Thanks for opening the issue! Sneaky bug!
